#pragma config(Sensor, dgtl2,  bump,           sensorTouch)
#pragma config(Motor,  port2,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
/*
//idea 1
setServo(servo1, 127); //set both servos to a closed position
setServo(servo2, 127);
while(true)
{
	if(sensorValue(linefollower)<500) //if sensor is covered
	{
		wait(2);
		setServo(servo1, -127); //open and close first door
		wait(1);
		setServo(servo1, 127);
		wait(1);
		setServo(servo2, -127); //open and close second door
		wait(1);
		setServo(servo2, 127);
		wait(4);
	}
	else //if sensor is not covered
	{
		setServo(servo1, 127); //close both doors
		setServo(servo2, 127);
	}
}
*/
//idea 2
	setServo(servo, 0);
while(true)
{
	wait(1);
	setServo(servo, 127);
	wait(1);
	setServo(servo, -127);
	wait(3);
}
}
