#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:A3_1_2_Part1
  Team Members: Christie, Devon
  Date: 3/4
  Section:


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces
	setServo(servoMotor,-127);
	wait(2);//servo to -127 for 2 sec
	setServo(servoMotor,-63);
	wait(3);//servo -63 for 3 sec
	setServo(servoMotor,0);
	wait(2);//servo 0 for 2 sec
	setServo(servoMotor,63);
	wait(3);//servo 63 for 3 sec
	setServo(servoMotor,127);
	wait(2);//servo 127 for 2 sec



}
