#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void LEDControl();//function declartation
task main()
{
	while(1==1)
	{
		LEDControl();//function control
	}
}
void LEDControl()//function def
{
	if (SensorValue(bumpSwitch)==1)
	{
		turnLEDOn(green);
	}
	else
	{
		turnLEDOff(green);
	}
}
